# Default of Credit Card Clients Dataset

Dataset can be found [here](https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients#) 

## Business Problem

A credit card company in Taiwan wants to know which feature is the biggest predictor in whether a customer will default their next payment. The company also wants to develop a machine learning algorithm in order to predict defaulters. They have emphasized that they want the model to predict as many defaulters. Although the costs of mistakenly predicting a non-defaulter as a defaulter is not high, the company wants the algorithm to at least predict half of the non-defaulters correctly.

### Import data, inspect, and rename columns

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500) #view all columns
pd.set_option('display.max_rows', 500) #view all columns

In [3]:
df = pd.read_excel('data/default_of_credit_card_clients.xls', header = 1)
print(df.columns)
print(df.shape)
df.head(20)

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')
(30000, 25)


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0    1      20000    2          2         1   24      2      2     -1     -1   
1    2     120000    2          2         2   26     -1      2      0      0   
2    3      90000    2          2         2   34      0      0      0      0   
3    4      50000    2          2         1   37      0      0      0      0   
4    5      50000    1          2         1   57     -1      0     -1      0   
5    6      50000    1          1         2   37      0      0      0      0   
6    7     500000    1          1         2   29      0      0      0      0   
7    8     100000    2          2         2   23      0     -1     -1      0   
8    9     140000    2          3         1   28      0      0      2      0   
9   10      20000    1          3         2   35     -2     -2     -2     -2   
10  11     200000    2          3         2   34      0      0      2      0   
11  12     260000    2          1         2   51     -1     -1     -1     -1   
12  13     630000    2          2         2   41     -1      0     -1     -1   
13  14      70000    1          2         2   30      1      2      2      0   
14  15     250000    1          1         2   29      0      0      0      0   
15  16      50000    2          3         3   23      1      2      0      0   
16  17      20000    1          1         2   24      0      0      2      2   
17  18     320000    1          1         1   49      0      0      0     -1   
18  19     360000    2          1         1   49      1     -2     -2     -2   
19  20     180000    2          1         2   29      1     -2     -2     -2   

    PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0      -2     -2       3913       3102        689          0          0   
1       0      2       2682       1725       2682       3272       3455   
2       0      0      29239      14027      13559      14331      14948   
3       0      0      46990      48233      49291      28314      28959   
4       0      0       8617       5670      35835      20940      19146   
5       0      0      64400      57069      57608      19394      19619   
6       0      0     367965     412023     445007     542653     483003   
7       0     -1      11876        380        601        221       -159   
8       0      0      11285      14096      12108      12211      11793   
9      -1     -1          0          0          0          0      13007   
10      0     -1      11073       9787       5535       2513       1828   
11     -1      2      12261      21670       9966       8517      22287   
12     -1     -1      12137       6500       6500       6500       6500   
13      0      2      65802      67369      65701      66782      36137   
14      0      0      70887      67060      63561      59696      56875   
15      0      0      50614      29173      28116      28771      29531   
16      2      2      15376      18010      17428      18338      17905   
17     -1     -1     253286     246536     194663      70074       5856   
18     -2     -2          0          0          0          0          0   
19     -2     -2          0          0          0          0          0   

    BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0           0         0       689         0         0         0         0   
1        3261         0      1000      1000      1000         0      2000   
2       15549      1518      1500      1000      1000      1000      5000   
3       29547      2000      2019      1200      1100      1069      1000   
4       19131      2000     36681     10000      9000       689       679   
5       20024      2500      1815       657      1000      1000       800   
6      473944     55000     40000     38000     20239     13750     13770   
7         567       380       601         0       581      1687      1542   
8        3719      3329         0       432      1000 

Rename poorly labeled columns

In [25]:
df.rename(columns={'default payment next month':'DEFAULT','PAY_0':'PAY_1'}, inplace=True)

### Data Set Information:

This research aimed at the case of customers’ default payments in Taiwan and compares the predictive accuracy of probability of default among six data mining methods. From the perspective of risk management, the result of predictive accuracy of the estimated probability of default will be more valuable than the binary result of classification - credible or not credible clients. Because the real probability of default is unknown, this study presented the novel “Sorting Smoothing Method” to estimate the real probability of default. With the real probability of default as the response variable (Y), and the predictive probability of default as the independent variable (X), the simple linear regression result (Y = A + BX) shows that the forecasting model produced by artificial neural network has the highest coefficient of determination; its regression intercept (A) is close to zero, and regression coefficient (B) to one. Therefore, among the six data mining techniques, artificial neural network is the only one that can accurately estimate the real probability of default.

Column Names and descriptions: 
- **ID**: Customer ID
- **LIMIT_BAL**: Amount of the given credit (NT dollar)
- **SEX**: 1 = male, 0 = female
- **EDUCATION**: 1 = graduate school; 2 = university; 3 = high school; 4 = others
- **MARRIAGE**: 1 = married; 2 = single; 3 = others
- **PAY_i**: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: Pay_1 = the repayment status in September, 2005; Pay_2 = the repayment status in August, 2005; . . .; Pay_6 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above
- **BILL_AMTi**: Amount of bill statement (NT dollar). Bill_AMT1 = amount of bill statement in September, 2005; Bill_AMT6 = amount of bill statement in August, 2005; . . .; Bill_AMT6 = amount of bill statement in April, 2005
- **PAY_AMTi**: Amount of previous payment (NT dollar). PAY_AMT1 = amount paid in September, 2005; PAY_AMT2 = amount paid in August, 2005; . . .;PAY_AMT6 = amount paid in April, 2005.
- **DEFAULT**: default payment next month

Code to inspect the dataframe's info, descriptive statistics, and value counts

In [26]:
# df.info()
# df.describe()
for col in df.columns:    # loop through columns
    print(f'"{col}" Value Counts:\n',
          df[col].value_counts(normalize=True).head(),
          '\n NumUnique:', df[col].nunique(), '\n')
# ascending = True for extraneous values

"ID" Value Counts:
 2047     0.000033
1322     0.000033
15629    0.000033
9486     0.000033
11535    0.000033
Name: ID, dtype: float64 
 NumUnique: 30000 

"LIMIT_BAL" Value Counts:
 50000     0.112167
20000     0.065867
30000     0.053667
80000     0.052233
200000    0.050933
Name: LIMIT_BAL, dtype: float64 
 NumUnique: 81 

"SEX" Value Counts:
 2    0.603733
1    0.396267
Name: SEX, dtype: float64 
 NumUnique: 2 

"EDUCATION" Value Counts:
 2    0.467667
1    0.352833
3    0.163900
5    0.009333
4    0.004100
Name: EDUCATION, dtype: float64 
 NumUnique: 7 

"MARRIAGE" Value Counts:
 2    0.532133
1    0.455300
3    0.010767
0    0.001800
Name: MARRIAGE, dtype: float64 
 NumUnique: 4 

"AGE" Value Counts:
 29    0.053500
27    0.049233
28    0.046967
30    0.046500
26    0.041867
Name: AGE, dtype: float64 
 NumUnique: 56 

"PAY_1" Value Counts:
  0    0.491233
-1    0.189533
 1    0.122933
-2    0.091967
 2    0.088900
Name: PAY_1, dtype: float64 
 NumUnique: 11 

"PAY_2" Value Counts

Notes on df.info():
- all dtypes are int64
- no explicit missing values

Notes on df.describe() and value counts:
- 78% default
- 60% women
- education: 47% grad school, 35% university, 16% high school, 1% 5 (unknown value), .5% others (4)
- marriage: 53% single, 46% married, 1% others, .2% 0 (unknown value)
- pay_i: 50-55% 0, 18-20% paid on time (-1)

Unique values of categorical features

In [27]:
for col in df.columns: # loop through columns
    if len(df[col].unique()) <= 10:
        print(f'"{col}" Unique:\n', df[col].unique())

"SEX" Unique:
 [2 1]
"EDUCATION" Unique:
 [2 1 3 5 4 6 0]
"MARRIAGE" Unique:
 [1 2 3 0]
"PAY_5" Unique:
 [-2  0 -1  2  3  5  4  7  8  6]
"PAY_6" Unique:
 [-2  2  0 -1  3  6  4  7  8  5]
"DEFAULT" Unique:
 [1 0]


- For EDUCATION and MARRIAGE, 0 likely means missing/unknown data. Very few rows have these values so we will drop.
- For EDUCATION, 5 and 6 are unknown/unspecified values. Very few rows have these values so we could probably drop these too, but it is also safe to assume these go with the "others", so we will replace these with 4.
- For PAY_i, -2 and 0 are unspecified. Many rows have these values, and it makes sense to assume these are indicating there to be no pay delay. -2, -1, and 0 will be changed to 0 to indicate no delay of payment.

### Handle missing/unknown values

In [28]:
df = df.loc[(df['EDUCATION'] != 0) & (df['MARRIAGE'] != 0)]

In [29]:
df.replace(to_replace ={**{f'PAY_{i}':{-1:0, -2:0} for i in range(1,7)},
                        **{'EDUCATION': {5: 4, 6: 4},**{'SEX':{2:0}}}}, inplace=True)

In [30]:
df.head(10)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1      20000    0          2         1   24      2      2      0      0   
1   2     120000    0          2         2   26      0      2      0      0   
2   3      90000    0          2         2   34      0      0      0      0   
3   4      50000    0          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57      0      0      0      0   
5   6      50000    1          1         2   37      0      0      0      0   
6   7     500000    1          1         2   29      0      0      0      0   
7   8     100000    0          2         2   23      0      0      0      0   
8   9     140000    0          3         1   28      0      0      2      0   
9  10      20000    1          3         2   35      0      0      0      0   

   PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0      0      0       3913       3102        689          0          0   
1      0      2       2682       1725       2682       3272       3455   
2      0      0      29239      14027      13559      14331      14948   
3      0      0      46990      48233      49291      28314      28959   
4      0      0       8617       5670      35835      20940      19146   
5      0      0      64400      57069      57608      19394      19619   
6      0      0     367965     412023     445007     542653     483003   
7      0      0      11876        380        601        221       -159   
8      0      0      11285      14096      12108      12211      11793   
9      0      0          0          0          0          0      13007   

   BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0          0         0       689         0         0         0         0   
1       3261         0      1000      1000      1000         0      2000   
2      15549      1518      1500      1000      1000      1000      5000   
3      29547      2000      2019      1200      1100      1069      1000   
4      19131      2000     36681     10000      9000       689       679   
5      20024      2500      1815       657      1000      1000       800   
6     473944     55000     40000     38000     20239     13750     13770   
7        567       380       601         0       581      1687      1542   
8       3719      3329         0       432      1000      1000      1000   
9      13912         0         0         0     13007      1122         0   

   DEFAULT  
0        1  
1        1  
2        0  
3        0  
4        0  
5        0  
6        0  
7        0  
8        0  
9        0

Inspect data again

In [15]:
# df.info()
# df.describe()
for col in df.columns:    # loop through columns
    print(f'"{col}" Value Counts:\n',
          df[col].value_counts(normalize=True).head(),
          '\n NumUnique:', df[col].nunique(), '\n')
# ascending = True for extraneous values

"ID" Value Counts:
 2047     0.000033
27943    0.000033
1290     0.000033
3339     0.000033
13580    0.000033
Name: ID, dtype: float64 
 NumUnique: 29932 

"LIMIT_BAL" Value Counts:
 50000     0.112154
20000     0.065916
30000     0.053722
80000     0.052185
200000    0.050748
Name: LIMIT_BAL, dtype: float64 
 NumUnique: 81 

"SEX" Value Counts:
 0    0.603568
1    0.396432
Name: SEX, dtype: float64 
 NumUnique: 2 

"EDUCATION" Value Counts:
 2    0.468529
1    0.353501
3    0.162802
4    0.015168
Name: EDUCATION, dtype: float64 
 NumUnique: 4 

"MARRIAGE" Value Counts:
 2    0.533008
1    0.456201
3    0.010791
Name: MARRIAGE, dtype: float64 
 NumUnique: 3 

"AGE" Value Counts:
 29    0.053588
27    0.049278
28    0.047007
30    0.046472
26    0.041862
Name: AGE, dtype: float64 
 NumUnique: 56 

"PAY_1" Value Counts:
 0    0.772718
1    0.122879
2    0.088968
3    0.010758
4    0.002539
Name: PAY_1, dtype: float64 
 NumUnique: 9 

"PAY_2" Value Counts:
 0    0.852031
2    0.130930
3  

#### Check Duplicates

In [16]:
print(df.duplicated().sum())
df['ID'].duplicated().sum()

0


0

### Save to csv

In [17]:
df.to_csv('data/clean_data.csv')